spring:
  data:
    redis:
      host: 82.157.203.231
      port: 6379
      password: redis-stack
  datasource:
    database: ry-vue
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.157.203.231/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: 200522
      max-lifetime: 600000
      connection-timeout: 600000
  ai:
    vectorstore:
      redis:
        index-name: stardew_index #向量库索引名字
        initialize-schema: true
    openai:
      base-url: https://open.bigmodel.cn/api/paas/v4/  # 智谱AI API地址
      api-key: 3d711fbeb0714d40bb74631fb2681283.9Mkjo8Q3TZMMj8BS # 智谱AI APIKey
      embedding:
        embeddings-path: embeddings # 重新设置智谱AI的向量模型路径，覆盖openAi默认配置
        options:
          model: embedding-3 # 使用embedding-3文本向量模型
          dimensions: 2048 # 向量维度
      chat:
        completions-path: chat/completions # 重新设置智谱AI的聊天模型路径，覆盖openAi默认配置
        options:
          model: GLM-4.5V # 使用GLM-4.5语言模型
          stream-usage: true
      image:
        options:
          model: GLM-4V
    #MCP inspector 测试使用的MCP Server配置信息
    mcp:
      server:
        type: sync
        sse-endpoint: /sse
        name: mcp-server
        enabled: true
  application:
    name: aurora-mcp-server
server:
  port: 8099
logging:
  level:
    com.aurora.mcp: debug